medicaloffice:
  # https://download.indamed.de/download.php?webcode=voll
  base:
    source: https://assets.bienert.tech/minio/public-repo/medical-office/base/moupd-0.0.0.exe

  update:
    source: https://assets.bienert.tech/minio/public-repo/medical-office/updates/moupd13944.exe